#!/usr/bin/env bash

# Configuration
remote_target=master
destination=_site

get-working-branch() {
    git status | head -n 1 | awk '{ print $NF }'
}

cleanup() {
    git checkout "$working_branch"
    git stash pop
}

trap cleanup EXIT

remote="$(git remote | head -n 1)"
working_branch="$(get-working-branch)"
git stash push --all
git branch --delete --force "$remote_target"
git checkout -b "$remote_target"

git add --force "$destination"
git commit --message "New version $(date)"
git filter-branch --subdirectory-filter "$destination/" --force

git push "$remote" "$remote_target" --force

# vim: ft=sh
