#!/usr/bin/env bash

# Configuration
remote_target=master
main_branch=develop
destination=_site

cleanup() {
    git checkout "$main_branch"
}

trap cleanup EXIT

remote="$(git remote | head -n 1)"
git branch -D "$remote_target"
git checkout -b "$remote_target"

git add -f "$destination"
git com -m "New version $(date)"
git filter-branch --subdirectory-filter "$destination/" -f

git push "$remote" "$remote_target" --force

# vim: ft=sh
